# Generated by Django 4.2.23 on 2025-07-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signuplog',
            old_name='e_mail_id',
            new_name='email_id',
        ),
    ]
