# Generated by Django 4.2.23 on 2025-07-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_rename_e_mail_id_signuplog_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuplog',
            name='occupation',
            field=models.CharField(default='customer', max_length=30),
        ),
    ]
