# Generated by Django 4.2.23 on 2025-08-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_signuplog_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='addcarlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='addimg/')),
            ],
        ),
    ]
